export const datasets = [
  {
    id: 1,
    tag: 'Goloka',
    title: 'igbo speech without transcription',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    format: 'TXT',
    size: '2.74 MB',
    created: '06/05/2025',
    link: 'https://drive.google.com/file/d/1TQiQGMw-wKUIqJSNcvDDIbs4xM5BVCBi/view?usp=sharing',
  },
  {
    id: 2,
    tag: 'Goloka',
    title: 'igbo text with translation',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    format: 'TXT',
    size: '2.04 MB',
    created: '06/07/2025',

    link: 'https://drive.google.com/file/d/1tMesnBIagNw9Y7TQ7J335NRVHcN7gQpY/view?usp=sharing',
  },
  {
    id: 3,
    tag: 'Goloka',
    title: 'isoko speech with translation',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    format: 'TXT',
    size: '1.65 MB',
    created: '06/09/2025',
    link: 'https://drive.google.com/file/d/1TBAl1pK8g_FuMZJAWhjzu4e3O-kfTrjR/view?usp=sharing',
  },
  {
    id: 4,
    tag: 'Goloka',
    title: 'isoko text with translation',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    format: 'TXT',
    size: '168.34 KB',
    created: '06/11/2025',
    link: 'https://drive.google.com/file/d/1OlsJE8wjA7vklpvfa6d5M5SD5J-mix9Q/view?usp=sharing',
  },
  {
    id: 5,
    tag: 'Goloka',
    title: 'urhobo speech with transcription',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    format: 'TXT',
    size: '1.32 MB',
    created: '06/13/2025',
    link: 'https://drive.google.com/file/d/1Q2re2THkdJ5SdqlvRH0effB8a56toEGk/view?usp=sharing',
  },
  {
    id: 6,
    tag: 'Goloka',
    title: 'urhobo text with translation',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    format: 'TXT',
    size: '1.21 MB',
    created: '06/15/2025',
    link: 'https://drive.google.com/file/d/1TFiufi1WAiSaIN0yHExer1tmpoDLZ3jX/view?usp=sharing',
  },
  {
    id: 7,
    tag: 'Goloka',
    title: 'yoruba speech with transcription',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    format: 'TXT',
    size: '1.88 MB',
    created: '06/17/2025',
    link: 'https://drive.google.com/file/d/1Gn9R0DKlBlBb-r5nhKyRBGYrt8mqs6Rp/view?usp=sharing',
  },
  {
    id: 8,
    tag: 'Goloka',
    title: 'yoruba text with translation',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    format: 'TXT',
    size: '1.54 MB',
    created: '06/19/2025',
    link: 'https://drive.google.com/file/d/1PyDvZ3kvTqjjKZtniFd_HXtDa6zLmgvg/view?usp=sharing',
  },
];
