export const datasets = [
  {
    id: 1,
    tag: 'Goloka',
    title: 'Igbo Speech without Transcription',
    desc: 'This dataset contains voice recording of translations of Igbo sentences into oral Igbo language. The text were first translated into Igbo and then transcribed volunteer with Igbo language expertise.',
    format: 'TXT',
    size: '2.74 MB',
    created: '06/05/2025',
    link: 'https://drive.google.com/file/d/1TQiQGMw-wKUIqJSNcvDDIbs4xM5BVCBi/view?usp=sharing',
  },
  {
    id: 2,
    tag: 'Goloka',
    title: 'Igbo Text with Translation',
    desc: 'This dataset contains texts derived from translation of 200 Igbo sentences into spoken Igbo language.',
    format: 'TXT',
    size: '2.04 MB',
    created: '06/07/2025',

    link: 'https://drive.google.com/file/d/1tMesnBIagNw9Y7TQ7J335NRVHcN7gQpY/view?usp=sharing',
  },

  {
    id: 3,
    tag: 'Goloka',
    title: 'Hausa Speech without Transcription',
    desc: 'This dataset contains voice recording of translations of Hausa sentences into oral Hausa language. The text were first translated into Hausa and then transcribed volunteer with Hausa language expertise.',
    format: 'TXT',
    size: '2.74 MB',
    created: '06/05/2025',
    link: 'https://drive.google.com/file/d/1x6mmTIYRnOSic_aSbkC_nOPUnMTT93aT/view?usp=sharing ',
  },
  {
    id: 4,
    tag: 'Goloka',
    title: 'Hausa Text with Translation',
    desc: 'This dataset contains texts derived from translation of 200 Hausa sentences into spoken Hausa language.',
    format: 'TXT',
    size: '2.04 MB',
    created: '06/07/2025',

    link: ' https://drive.google.com/file/d/1RNIgK1k4hOiiAr7w4_ky-D84WmKYk2yD/view?usp=sharing',
  },
  {
    id: 10,
    tag: 'Goloka',
    title: 'Isoko Speech with Translation',
    desc: 'This dataset contains texts derived from translation of 200 Isoko sentences into spoken Isoko language.',
    format: 'TXT',
    size: '1.65 MB',
    created: '06/09/2025',
    link: 'https://drive.google.com/file/d/1TBAl1pK8g_FuMZJAWhjzu4e3O-kfTrjR/view?usp=sharing',
  },
  {
    id: 5,
    tag: 'Goloka',
    title: 'Isoko Text with Transcription',
    desc: 'This dataset contains voice recording of translations of Isoko sentences into oral Isoko language. The text were first translated into Isoko and then transcribed volunteer with Isoko language expertise.',
    format: 'TXT',
    size: '168.34 KB',
    created: '06/11/2025',
    link: 'https://drive.google.com/file/d/1OlsJE8wjA7vklpvfa6d5M5SD5J-mix9Q/view?usp=sharing',
  },
  {
    id: 6,
    tag: 'Goloka',
    title: 'Urhobo Speech with Transcription',
    desc: 'This dataset contains voice recording of translations of Hausa sentences into oral Hausa language. The text were first translated into Hausa and then transcribed volunteer with Hausa language expertise.',
    format: 'TXT',
    size: '1.32 MB',
    created: '06/13/2025',
    link: 'https://drive.google.com/file/d/1Q2re2THkdJ5SdqlvRH0effB8a56toEGk/view?usp=sharing',
  },
  {
    id: 7,
    tag: 'Goloka',
    title: 'Urhobo Text with Translation',
    desc: 'This dataset contains texts derived from translation of 200 Urhobo sentences into spoken Urhobo language.',
    format: 'TXT',
    size: '1.21 MB',
    created: '06/15/2025',
    link: 'https://drive.google.com/file/d/1TFiufi1WAiSaIN0yHExer1tmpoDLZ3jX/view?usp=sharing',
  },
  {
    id: 8,
    tag: 'Goloka',
    title: 'Yoruba Speech with Transcription',
    desc: 'This dataset contains voice recording of translations of Yoruba sentences into oral Yoruba language. The text were first translated into Yoruba and then transcribed volunteer with Yoruba language expertise.',
    format: 'TXT',
    size: '1.88 MB',
    created: '06/17/2025',
    link: 'https://drive.google.com/file/d/1Gn9R0DKlBlBb-r5nhKyRBGYrt8mqs6Rp/view?usp=sharing',
  },
  {
    id: 9,
    tag: 'Goloka',
    title: 'Yoruba Text with Translation',
    desc: 'This dataset contains texts derived from translation of 200 Yoruba sentences into spoken Yoruba language.',
    format: 'TXT',
    size: '1.54 MB',
    created: '06/19/2025',
    link: 'https://drive.google.com/file/d/1PyDvZ3kvTqjjKZtniFd_HXtDa6zLmgvg/view?usp=sharing',
  },
];
